Create a 1D array of numbers from 0 to 9

In [34]:
import numpy

arr = numpy.array([0,1,2,3,4,5,6,7,8,9])

print(arr)

[0 1 2 3 4 5 6 7 8 9]


Create a 2D array with shape (3, 3), where values range from 1 to 9.


In [19]:
import numpy as np

arr2 = np.array([[1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])

print(arr2)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


Create a 3D array of shape (2, 3, 4) filled with random integers from 1 to 100.

In [31]:
import numpy as np

arr3 = np.array([[[1, 2,0], [2,1,0], [4,3,0]],
 [[1,2,3], [4,3,2], [3,3,3]],
 [[4,3,2], [1,2,3], [4,4,4]]])

print(arr3)

[[[1 2 0]
  [2 1 0]
  [4 3 0]]

 [[1 2 3]
  [4 3 2]
  [3 3 3]]

 [[4 3 2]
  [1 2 3]
  [4 4 4]]]


Given the array arr2 from Task 1, extract the second row.


In [28]:
second_row = arr2[1]
print(second_row)

[1 2 3 4 5 6 7 8 9]


Extract the element at the 3rd row and 2nd column of arr2.

In [29]:


element = arr2[2, 1]
print(element)


2


Extract all elements from the 3D array arr3 at the first index (0th layer)

In [32]:
firstIndex=arr3[0]
print(firstIndex)

[[1 2 0]
 [2 1 0]
 [4 3 0]]


Add 10 to each element of arr1.

In [44]:
for i in range(10):
    arr[i] += 10;
print(arr);

[10 11 12 13 14 15 16 17 18 19]


Multiply each element of arr2 by 2.

In [45]:


arr2_multiplied = arr2 * 2
print(arr2_multiplied)


[[ 2  4  6  8 10 12 14 16 18]
 [ 2  4  6  8 10 12 14 16 18]
 [ 2  4  6  8 10 12 14 16 18]]
